# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - sync

sync_repo:
  stage: sync
  variables:
    GIT_STRATEGY: none

  script:
    - git clone --branch main https://oauth2:${REPO_ACCESS_TOKEN}@gitlab.wujia.lllidancloud.com:35678/group-1/1.git

    # 2. 进入目录
    - cd 1
    - |
      if [ ! -d "ios" ]; then
        echo "📁 ios 目录不存在，正在自动创建..."
        mkdir "ios"
      else
        echo "♻️  ios 目录已存在，正在删除旧的 fastlane 目录..."
        rm -rf "ios/fastlane"
      fi

    - echo "🚚 将 fastlane 目录复制到 ios/ 下..."
    - cp -r /app/fastlane ios/

    # 3. 示例操作（你可以改这里）
    - ls -al

    - rm -rf .gitlab-ci.yml

    - ls -al

    - 'echo "token length: ${#GITHUB_TOKEN}"'

    # 2. 确保 tags 可见（浅克隆后再 fetch tags）
    - git fetch --tags

    # 在 git push 之前加入这三行配置
    - git config --global http.postBuffer 524288000
    - git config --global http.lowSpeedLimit 0
    - git config --global http.lowSpeedTime 999999

    # 3. 配置 GitHub remote
    - git remote add github https://${GITHUB_TOKEN}@github.com/sklm-roce-1k121/repo-1-x-s-7-L-5-2-0-x-R.git

    # 4. 推 main (无限重试，直到成功)
    - until git push --force github main:main; do echo "网络错误，5秒后重试 main 推送..."; sleep 5; done

    # 5. 推所有 tags (无限重试，直到成功)
    - until git push --force github --tags; do echo "网络错误，5秒后重试 tags 推送..."; sleep 5; done